# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

def shared_pods

  inhibit_all_warnings!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTAnimation',
    'RCTBlob',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'CxxBridge',
    'DevSupport',
  ]
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNADBMobile', path: '../node_modules/react-native-adbmobile/ios'
end

target 'RNADBMobileExample' do
  shared_pods
end

target 'RNADBMobileExampleTests' do
  shared_pods
end

target 'RNADBMobileExample-tvOS' do
  shared_pods
end

target 'RNADBMobileExample-tvOSTests' do
  shared_pods
end
